// Generated by scripts/sync-provider-registry.ts. Run bun run provider:sync.
export const sdkScaffoldVersion: string = "1.32.0";

interface ProviderTemplateMetadata {
  readonly packageName: string;
  readonly packageVersion: string;
  readonly factoryName: string;
  readonly envName: string;
  readonly defaultModel: string;
}

export const providerTemplates: Readonly<Record<"vertex" | "openai" | "xai" | "meta" | "anthropic" | "gemini" | "kimi" | "deepseek" | "zai", ProviderTemplateMetadata>> = {
  "vertex": {
    "packageName": "@zhivex-ai/vertex",
    "packageVersion": "1.2.7",
    "factoryName": "createVertex",
    "envName": "GOOGLE_CLOUD_PROJECT",
    "defaultModel": "gemini-3.7-flash"
  },
  "openai": {
    "packageName": "@zhivex-ai/openai",
    "packageVersion": "0.16.0",
    "factoryName": "createOpenAI",
    "envName": "OPENAI_API_KEY",
    "defaultModel": "gpt-6-astra"
  },
  "xai": {
    "packageName": "@zhivex-ai/xai",
    "packageVersion": "0.2.11",
    "factoryName": "createXAI",
    "envName": "XAI_API_KEY",
    "defaultModel": "grok-4.5"
  },
  "meta": {
    "packageName": "@zhivex-ai/meta",
    "packageVersion": "0.2.9",
    "factoryName": "createMeta",
    "envName": "MODEL_API_KEY",
    "defaultModel": "muse-spark-1.2"
  },
  "anthropic": {
    "packageName": "@zhivex-ai/anthropic",
    "packageVersion": "0.14.0",
    "factoryName": "createAnthropic",
    "envName": "ANTHROPIC_API_KEY",
    "defaultModel": "claude-sonnet-5"
  },
  "gemini": {
    "packageName": "@zhivex-ai/gemini",
    "packageVersion": "0.13.0",
    "factoryName": "createGemini",
    "envName": "GEMINI_API_KEY",
    "defaultModel": "gemini-3.6-flash"
  },
  "kimi": {
    "packageName": "@zhivex-ai/kimi",
    "packageVersion": "0.7.11",
    "factoryName": "createKimi",
    "envName": "KIMI_API_KEY",
    "defaultModel": "kimi-k3"
  },
  "deepseek": {
    "packageName": "@zhivex-ai/deepseek",
    "packageVersion": "0.5.7",
    "factoryName": "createDeepSeek",
    "envName": "DEEPSEEK_API_KEY",
    "defaultModel": "deepseek-v4-flash"
  },
  "zai": {
    "packageName": "@zhivex-ai/zai",
    "packageVersion": "0.2.4",
    "factoryName": "createZAI",
    "envName": "ZAI_API_KEY",
    "defaultModel": "glm-5.3"
  }
};
