import { describe, expect, it } from "vitest";

import * as sdk from "../src/index.js";

describe("sdk public surface", () => {
  it("exports the shared helpers from core", () => {
    expect(sdk.generateText).toBeTypeOf("function");
    expect(sdk.createAgent).toBeTypeOf("function");
    expect(sdk.createAgentHandoff).toBeTypeOf("function");
    expect(sdk.resumeAgent).toBeTypeOf("function");
    expect(sdk.streamText).toBeTypeOf("function");
    expect(sdk.runAgent).toBeTypeOf("function");
    expect(sdk.runAgentHandoff).toBeTypeOf("function");
    expect(sdk.streamAgent).toBeTypeOf("function");
    expect(sdk.streamLiveAgent).toBeTypeOf("function");
    expect(sdk.createInMemoryAgentRunStore).toBeTypeOf("function");
    expect(sdk.createFileAgentRunStore).toBeTypeOf("function");
    expect(sdk.createSqliteAgentRunStore).toBeTypeOf("function");
    expect(sdk.createPostgresAgentRunStore).toBeTypeOf("function");
    expect(sdk.createInMemoryAgentMemoryStore).toBeTypeOf("function");
    expect(sdk.createFileAgentMemoryStore).toBeTypeOf("function");
    expect(sdk.createSqliteAgentMemoryStore).toBeTypeOf("function");
    expect(sdk.createPostgresAgentMemoryStore).toBeTypeOf("function");
    expect(sdk.getAgentApprovalRequests).toBeTypeOf("function");
    expect(sdk.getAgentApprovalRequestFromPart).toBeTypeOf("function");
    expect(sdk.createAgentApprovalMessage).toBeTypeOf("function");
    expect(sdk.agentApprovalResponsePart).toBeTypeOf("function");
    expect(sdk.getAgentCapabilities).toBeTypeOf("function");
    expect(sdk.getAgentSupportTier).toBeTypeOf("function");
    expect(sdk.getHostedToolClass).toBeTypeOf("function");
    expect(sdk.toUIAgentStreamResponse).toBeTypeOf("function");
    expect(sdk.generateObject).toBeTypeOf("function");
    expect(sdk.streamObject).toBeTypeOf("function");
    expect(sdk.embed).toBeTypeOf("function");
    expect(sdk.embedMany).toBeTypeOf("function");
    expect(sdk.transcribeAudio).toBeTypeOf("function");
    expect(sdk.generateSpeech).toBeTypeOf("function");
    expect(sdk.generateGroundedText).toBeTypeOf("function");
    expect(sdk.toTextStreamResponse).toBeTypeOf("function");
    expect(sdk.toUIMessageStreamResponse).toBeTypeOf("function");
    expect(sdk.toUIMessage).toBeTypeOf("function");
    expect(sdk.wrapLanguageModel).toBeTypeOf("function");
    expect(sdk.createTelemetryMiddleware).toBeTypeOf("function");
    expect(sdk.createCachedGenerateMiddleware).toBeTypeOf("function");
    expect(sdk.createCircuitBreakerMiddleware).toBeTypeOf("function");
    expect(sdk.createFileGenerateCache).toBeTypeOf("function");
    expect(sdk.createToolRegistry).toBeTypeOf("function");
    expect(sdk.createMcpToolRegistry).toBeTypeOf("function");
    expect(sdk.createOtelObserver).toBeTypeOf("function");
    expect(sdk.createOtelAgentObserver).toBeTypeOf("function");
    expect(sdk.createOtelTelemetryMiddleware).toBeTypeOf("function");
    expect(sdk.createMcpToolSet).toBeTypeOf("function");
    expect(sdk.createModelCatalog).toBeTypeOf("function");
    expect(sdk.parseUIMessageRequest).toBeTypeOf("function");
    expect(sdk.tool).toBeTypeOf("function");
    expect(sdk.system).toBeTypeOf("function");
    expect(sdk.user).toBeTypeOf("function");
    expect(sdk.assistant).toBeTypeOf("function");
  });

  it("does not re-export provider factories", () => {
    expect("createOpenAI" in sdk).toBe(false);
    expect("createDeepSeek" in sdk).toBe(false);
    expect("createAzureOpenAI" in sdk).toBe(false);
    expect("createAnthropic" in sdk).toBe(false);
    expect("createGemini" in sdk).toBe(false);
    expect("createOpenRouter" in sdk).toBe(false);
    expect("createBedrock" in sdk).toBe(false);
    expect("createOllama" in sdk).toBe(false);
    expect("createGateway" in sdk).toBe(false);
  });
});
