import { describe, expect, it } from "vitest";

import * as sdk from "../src/index.js";

describe("sdk public surface", () => {
  it("exports the shared helpers from core", () => {
    expect(sdk.generateText).toBeTypeOf("function");
    expect(sdk.AdvancedToolRegistry).toBeTypeOf("function");
    expect(sdk.cancelAgentRun).toBeTypeOf("function");
    expect(sdk.cancelAgentRunTree).toBeTypeOf("function");
    expect(sdk.createAdvancedToolRegistry).toBeTypeOf("function");
    expect(sdk.getApiStability).toBeTypeOf("function");
    expect(sdk.listApiStability).toBeTypeOf("function");
    expect(sdk.API_STABILITY_MANIFEST.createRunner.stability).toBe("stable");
    expect(sdk.createAgent).toBeTypeOf("function");
    expect(sdk.createAgentEvaluationFixture).toBeTypeOf("function");
    expect(sdk.createAgentEvaluationReport).toBeTypeOf("function");
    expect(sdk.createAgentRunSnapshot).toBeTypeOf("function");
    expect(sdk.createAgentRunTreeSnapshot).toBeTypeOf("function");
    expect(sdk.createAgentTraceArtifact).toBeTypeOf("function");
    expect(sdk.createAgentTraceCollector).toBeTypeOf("function");
    expect(sdk.createHierarchicalAgentTrace).toBeTypeOf("function");
    expect(sdk.createAgentHandoff).toBeTypeOf("function");
    expect(sdk.createApprovalPolicy).toBeTypeOf("function");
    expect(sdk.createBudgetGuard).toBeTypeOf("function");
    expect(sdk.createMockLanguageModel).toBeTypeOf("function");
    expect(sdk.createMockTool).toBeTypeOf("function");
    expect(sdk.createProviderSupportDriftReport).toBeTypeOf("function");
    expect(sdk.createProviderSupportMatrix).toBeTypeOf("function");
    expect(sdk.createProductionSafetyPolicy).toBeTypeOf("function");
    expect(sdk.createProductionTraceCollector).toBeTypeOf("function");
    expect(sdk.createProductionTraceOptions).toBeTypeOf("function");
    expect(sdk.chunkText).toBeTypeOf("function");
    expect(sdk.cosineSimilarity).toBeTypeOf("function");
    expect(sdk.createRetrievalContextMessage).toBeTypeOf("function");
    expect(sdk.embedRetrievalDocuments).toBeTypeOf("function");
    expect(sdk.formatRetrievedContext).toBeTypeOf("function");
    expect(sdk.rankRetrievedDocuments).toBeTypeOf("function");
    expect(sdk.retrieveContext).toBeTypeOf("function");
    expect(sdk.createRedactionPolicy).toBeTypeOf("function");
    expect(sdk.createSafetyPolicy).toBeTypeOf("function");
    expect(sdk.createSubAgentTool).toBeTypeOf("function");
    expect(sdk.prepareSubagentsForAgent).toBeTypeOf("function");
    expect(sdk.resumeAgent).toBeTypeOf("function");
    expect(sdk.streamText).toBeTypeOf("function");
    expect(sdk.runAgent).toBeTypeOf("function");
    expect(sdk.runAgentGroup).toBeTypeOf("function");
    expect(sdk.runAgentHandoff).toBeTypeOf("function");
    expect(sdk.streamAgent).toBeTypeOf("function");
    expect(sdk.streamLiveAgent).toBeTypeOf("function");
    expect(sdk.createInMemoryAgentRunStore).toBeTypeOf("function");
    expect(sdk.createFileAgentRunStore).toBeTypeOf("function");
    expect(sdk.createSqliteAgentRunStore).toBeTypeOf("function");
    expect(sdk.createPostgresAgentRunStore).toBeTypeOf("function");
    expect(sdk.createInMemoryAgentMemoryStore).toBeTypeOf("function");
    expect(sdk.createFileAgentMemoryStore).toBeTypeOf("function");
    expect(sdk.createSqliteAgentMemoryStore).toBeTypeOf("function");
    expect(sdk.createPostgresAgentMemoryStore).toBeTypeOf("function");
    expect(sdk.getAgentApprovalRequests).toBeTypeOf("function");
    expect(sdk.getAgentApprovalRequestFromPart).toBeTypeOf("function");
    expect(sdk.createAgentApprovalMessage).toBeTypeOf("function");
    expect(sdk.agentApprovalResponsePart).toBeTypeOf("function");
    expect(sdk.getAgentCapabilities).toBeTypeOf("function");
    expect(sdk.getAgentSupportTier).toBeTypeOf("function");
    expect(sdk.inspectProviderAgentSupport).toBeTypeOf("function");
    expect(sdk.applySafetyPolicyToAgent).toBeTypeOf("function");
    expect(sdk.judgeAgentEvaluation).toBeTypeOf("function");
    expect(sdk.replayAgentRun).toBeTypeOf("function");
    expect(sdk.renderProviderSupportMatrix).toBeTypeOf("function");
    expect(sdk.runAgentEvaluation).toBeTypeOf("function");
    expect(sdk.getHostedToolClass).toBeTypeOf("function");
    expect(sdk.toUIAgentStreamResponse).toBeTypeOf("function");
    expect(sdk.generateObject).toBeTypeOf("function");
    expect(sdk.streamObject).toBeTypeOf("function");
    expect(sdk.embed).toBeTypeOf("function");
    expect(sdk.embedMany).toBeTypeOf("function");
    expect(sdk.estimateAgentRunCost).toBeTypeOf("function");
    expect(sdk.estimateTokenCost).toBeTypeOf("function");
    expect(sdk.transcribeAudio).toBeTypeOf("function");
    expect(sdk.generateSpeech).toBeTypeOf("function");
    expect(sdk.generateGroundedText).toBeTypeOf("function");
    expect(sdk.toTextStreamResponse).toBeTypeOf("function");
    expect(sdk.toUIMessageStreamResponse).toBeTypeOf("function");
    expect(sdk.toUIMessage).toBeTypeOf("function");
    expect(sdk.wrapLanguageModel).toBeTypeOf("function");
    expect(sdk.createTelemetryMiddleware).toBeTypeOf("function");
    expect(sdk.createCachedGenerateMiddleware).toBeTypeOf("function");
    expect(sdk.createCircuitBreakerMiddleware).toBeTypeOf("function");
    expect(sdk.createFileGenerateCache).toBeTypeOf("function");
    expect(sdk.createToolRegistry).toBeTypeOf("function");
    expect(sdk.createToolPermissionPreset).toBeTypeOf("function");
    expect(sdk.createToolTestFixture).toBeTypeOf("function");
    expect(sdk.createHttpTool).toBeTypeOf("function");
    expect(sdk.inspectToolRegistry).toBeTypeOf("function");
    expect(sdk.recordToolTestFixture).toBeTypeOf("function");
    expect(sdk.runToolTestFixture).toBeTypeOf("function");
    expect(sdk.createAgentCapsule).toBeTypeOf("function");
    expect(sdk.inspectAgentCapsule).toBeTypeOf("function");
    expect(sdk.createAgentToolPolicy).toBeTypeOf("function");
    expect(sdk.createAgentApprovalQueue).toBeTypeOf("function");
    expect(sdk.createAgentRunLedger).toBeTypeOf("function");
    expect(sdk.diffAgentRunLedgers).toBeTypeOf("function");
    expect(sdk.promoteAgentGoldenTrace).toBeTypeOf("function");
    expect(sdk.selectAgentModel).toBeTypeOf("function");
    expect(sdk.createAgentCapabilityRouter).toBeTypeOf("function");
    expect(sdk.createAgentControlPlane).toBeTypeOf("function");
    expect(sdk.testToolDefinition).toBeTypeOf("function");
    expect(sdk.testToolRegistry).toBeTypeOf("function");
    expect(sdk.createMcpToolRegistry).toBeTypeOf("function");
    expect(sdk.createOtelObserver).toBeTypeOf("function");
    expect(sdk.createOtelAgentObserver).toBeTypeOf("function");
    expect(sdk.createOtelTelemetryMiddleware).toBeTypeOf("function");
    expect(sdk.createMcpToolSet).toBeTypeOf("function");
    expect(sdk.createModelCatalog).toBeTypeOf("function");
    expect(sdk.runAgentEvaluationFixture).toBeTypeOf("function");
    expect(sdk.summarizeAgentTrace).toBeTypeOf("function");
    expect(sdk.parseUIMessageRequest).toBeTypeOf("function");
    expect(sdk.tool).toBeTypeOf("function");
    expect(sdk.system).toBeTypeOf("function");
    expect(sdk.user).toBeTypeOf("function");
    expect(sdk.assistant).toBeTypeOf("function");
  });

  it("re-exports API stability metadata from core", () => {
    expect(sdk.getApiStability("generateText")?.stability).toBe("stable");
    expect(sdk.getApiStability("createRunner")?.stability).toBe("stable");
    expect(sdk.getApiStability("createProductionSafetyPolicy")?.stability).toBe("stable");
    expect(sdk.getApiStability("createProductionTraceCollector")?.stability).toBe("stable");
    expect(sdk.getApiStability("createProductionTraceOptions")?.stability).toBe("stable");
    expect(sdk.getApiStability("chunkText")?.stability).toBe("stable");
    expect(sdk.getApiStability("embedRetrievalDocuments")?.stability).toBe("stable");
    expect(sdk.getApiStability("retrieveContext")?.stability).toBe("stable");
    expect(sdk.getApiStability("createInMemorySessionService")?.stability).toBe("stable");
    expect(sdk.getApiStability("createFileSessionService")?.stability).toBe("stable");
    expect(sdk.getApiStability("createWorkflow")?.stability).toBe("beta");
    expect(sdk.getApiStability("createFileArtifactService")?.stability).toBe("beta");
    expect(sdk.getApiStability("createFileWorkflowStateService")?.stability).toBe("beta");
    expect(sdk.getApiStability("verifyArtifactIntegrity")?.stability).toBe("beta");
    expect(sdk.getApiStability("createAgentControlPlane")?.stability).toBe("beta");
    expect(sdk.getApiStability("createAgentCapsule")?.stability).toBe("beta");
    expect(sdk.getApiStability("createAgentRunLedger")?.stability).toBe("beta");
    expect(sdk.getApiStability("createAdvancedToolRegistry")?.stability).toBe("experimental");
  });

  it("does not re-export provider factories", () => {
    expect("createOpenAI" in sdk).toBe(false);
    expect("createDeepSeek" in sdk).toBe(false);
    expect("createAzureOpenAI" in sdk).toBe(false);
    expect("createAnthropic" in sdk).toBe(false);
    expect("createGemini" in sdk).toBe(false);
    expect("createOpenRouter" in sdk).toBe(false);
    expect("createBedrock" in sdk).toBe(false);
    expect("createOllama" in sdk).toBe(false);
    expect("createGateway" in sdk).toBe(false);
  });
});
