export type ApiStabilityLevel = "stable" | "beta" | "experimental";

export interface ApiStabilityEntry {
  symbol: string;
  stability: ApiStabilityLevel;
}

const stableSymbols = [
  "ConfigurationError",
  "GuardrailTriggeredError",
  "ParseError",
  "ProviderHTTPError",
  "ToolRegistry",
  "UnsupportedFeatureError",
  "ValidationError",
  "ZhivexAIError",
  "agentApprovalResponsePart",
  "applySafetyPolicyToAgent",
  "assistant",
  "cancelAgentRun",
  "cancelAgentRunTree",
  "collectUIMessage",
  "createAgent",
  "createAgentApprovalMessage",
  "createAgentEvaluationFixture",
  "createAgentEvaluationReport",
  "createAgentHandoff",
  "createAgentHandoffMessage",
  "createAgentRunSnapshot",
  "createAgentRunTreeSnapshot",
  "createAgentTraceArtifact",
  "createAgentTraceCollector",
  "createApprovalPolicy",
  "createBudgetGuard",
  "createCachedGenerateMiddleware",
  "createCircuitBreakerMiddleware",
  "createFileAgentMemoryStore",
  "createFileAgentRunStore",
  "createFileGenerateCache",
  "createFileSessionService",
  "createHierarchicalAgentTrace",
  "createInMemoryAgentMemoryStore",
  "createInMemoryAgentRunStore",
  "createInMemoryGenerateCache",
  "createInMemorySessionService",
  "createMcpToolSet",
  "createMockLanguageModel",
  "createMockTool",
  "createPostgresAgentMemoryStore",
  "createPostgresAgentRunStore",
  "createPostgresSessionService",
  "createProviderSupportDriftReport",
  "createProviderSupportMatrix",
  "createRedactionPolicy",
  "createRunner",
  "createSafetyPolicy",
  "createSqliteAgentMemoryStore",
  "createSqliteAgentRunStore",
  "createSqliteSessionService",
  "createSubAgentTool",
  "createTelemetryMiddleware",
  "createTextMessage",
  "createToolRegistry",
  "createUIMessageJsonResponse",
  "createUIMessageLinesResponse",
  "embed",
  "embedMany",
  "estimateAgentRunCost",
  "estimateTokenCost",
  "fromUIMessage",
  "fromUIMessages",
  "generateGroundedText",
  "generateImage",
  "generateMusic",
  "generateObject",
  "generateSpeech",
  "generateText",
  "generateVideo",
  "getAgentApprovalRequestFromPart",
  "getAgentApprovalRequests",
  "getTextFromMessages",
  "getTextFromParts",
  "getToolCallsFromEvents",
  "inspectProviderAgentSupport",
  "isCallableToolDefinition",
  "isToolRegistry",
  "judgeAgentEvaluation",
  "mergeAbortSignals",
  "migrateAgentSessionRecord",
  "normalizeAgentSession",
  "pruneFileSessionStore",
  "normalizeFinishReason",
  "normalizeMessages",
  "parseUIMessageRequest",
  "prepareSubagentsForAgent",
  "providerDataPart",
  "renderProviderSupportMatrix",
  "replayAgentRun",
  "resultMessages",
  "resumeAgent",
  "runAgent",
  "runAgentEvaluation",
  "runAgentEvaluationFixture",
  "runAgentGroup",
  "runAgentHandoff",
  "SESSION_SCHEMA_VERSION",
  "serializeJsonValue",
  "serializeUIMessage",
  "streamAgent",
  "streamObject",
  "streamSSE",
  "streamText",
  "summarizeAgentTrace",
  "system",
  "textPart",
  "toSSEResponse",
  "toSSEStream",
  "toTextReadableStream",
  "toTextStreamResponse",
  "toToolSet",
  "toUIAgentStreamResponse",
  "toUIMessage",
  "toUIMessageStream",
  "toUIMessageStreamResponse",
  "toUIMessages",
  "tool",
  "toolCallPart",
  "toolResultPart",
  "toolResultPayload",
  "transcribeAudio",
  "user",
  "validateMessageParts",
  "withRetry",
  "withTimeoutSignal",
  "wrapLanguageModel"
] as const;

const betaSymbols = [
  "API_STABILITY_MANIFEST",
  "ARTIFACT_SCHEMA_VERSION",
  "ConflictError",
  "OTelObserver",
  "OTelSpanHandle",
  "WORKFLOW_RUN_STATE_SCHEMA_VERSION",
  "WORKFLOW_STATE_RECORD_SCHEMA_VERSION",
  "cancelBatch",
  "cleanupFileArtifactStore",
  "compareWorkflowEvaluationReports",
  "createBase64ArtifactData",
  "createBatch",
  "createContextCache",
  "createExternalArtifactReference",
  "createFileArtifactService",
  "createFileSearchStore",
  "createFileWorkflowStateService",
  "createInMemoryArtifactService",
  "createInMemoryWorkflowStateService",
  "createInteraction",
  "createMcpToolRegistry",
  "createModelCatalog",
  "createOtelAgentObserver",
  "createOtelObserver",
  "createOtelTelemetryMiddleware",
  "createPostgresArtifactService",
  "createPostgresWorkflowStateService",
  "createProviderAdapter",
  "createSqliteArtifactService",
  "createSqliteWorkflowStateService",
  "createWorkflow",
  "createWorkflowEvaluationDiffReport",
  "createWorkflowEvaluationFixture",
  "createWorkflowEvaluationReport",
  "defaultModelCatalog",
  "deleteBatch",
  "deleteContextCache",
  "deleteFile",
  "deleteFileSearchStore",
  "deserializeUIMessage",
  "fetchPredictionOperation",
  "getAgentCapabilities",
  "getAgentSupportTier",
  "getApiStability",
  "getBatch",
  "getContextCache",
  "getFile",
  "getFileSearchStore",
  "getHostedToolClass",
  "getInteraction",
  "hostedTool",
  "importFileToFileSearchStore",
  "inspectFileArtifactStore",
  "isHostedToolClass",
  "isHostedToolDefinition",
  "judgeWorkflowEvaluation",
  "listApiStability",
  "listBatches",
  "listContextCaches",
  "listFileSearchStores",
  "listFiles",
  "loadWorkflowState",
  "migrateArtifactRecord",
  "migrateWorkflowRunState",
  "migrateWorkflowStateRecord",
  "normalizeArtifactRecord",
  "normalizeWorkflowRunState",
  "normalizeWorkflowStateRecord",
  "predictLongRunning",
  "predictRaw",
  "pruneFileArtifactStore",
  "pruneFileWorkflowStateStore",
  "replayWorkflowRun",
  "runWorkflow",
  "runWorkflowEvaluation",
  "runWorkflowEvaluationFixture",
  "saveWorkflowEvaluationReportAsArtifact",
  "saveWorkflowOutputsAsArtifacts",
  "saveWorkflowReplayAsArtifact",
  "saveWorkflowState",
  "streamInteraction",
  "uploadFile",
  "uploadToFileSearchStore",
  "verifyArtifactIntegrity",
  "verifyArtifactRecordIntegrity"
] as const;

const experimentalSymbols = [
  "AdvancedToolRegistry",
  "CallbackRealtimeSession",
  "createAdvancedToolRegistry",
  "createHttpTool",
  "createToolPermissionPreset",
  "createToolTestFixture",
  "encodeAudioFrame",
  "encodeMediaFrame",
  "googleCodeExecutionTool",
  "googleComputerUseTool",
  "googleFileSearchTool",
  "googleSearchTool",
  "googleUrlContextTool",
  "inspectToolRegistry",
  "openWebSocketConnection",
  "recordToolTestFixture",
  "runToolTestFixture",
  "streamLiveAgent",
  "testToolDefinition",
  "testToolRegistry",
  "unsupportedBrowserToken"
] as const;

const createManifest = () => {
  const manifest: Record<string, ApiStabilityEntry> = {};

  for (const [stability, symbols] of [
    ["stable", stableSymbols],
    ["beta", betaSymbols],
    ["experimental", experimentalSymbols]
  ] as const) {
    for (const symbol of symbols) {
      if (manifest[symbol]) {
        throw new Error(`Duplicate API stability entry for ${symbol}`);
      }
      manifest[symbol] = { symbol, stability };
    }
  }

  return Object.freeze(manifest);
};

export const API_STABILITY_MANIFEST = createManifest();

export const getApiStability = (symbolName: string): ApiStabilityEntry | undefined =>
  API_STABILITY_MANIFEST[symbolName];

export const listApiStability = (level?: ApiStabilityLevel): ApiStabilityEntry[] =>
  Object.values(API_STABILITY_MANIFEST)
    .filter((entry) => level === undefined || entry.stability === level)
    .sort((a, b) => a.symbol.localeCompare(b.symbol));
