export type ApiStabilityLevel = "stable" | "beta" | "experimental";

export interface ApiStabilityEntry {
  symbol: string;
  stability: ApiStabilityLevel;
}

const stableSymbols = [
  "API_STABILITY_MANIFEST",
  "AGENT_CONTROL_PLANE_SCHEMA_VERSION",
  "AGENT_RUN_STATE_SCHEMA_VERSION",
  "ARTIFACT_SCHEMA_VERSION",
  "DEFAULT_ARTIFACT_SERVICE_LIMITS",
  "MODEL_CATALOG_CONTRACT_VERSION",
  "MODEL_CATALOG_SCHEMA_VERSION",
  "OTEL_GENAI_CONTRACT_VERSION",
  "OTEL_GENAI_SEMCONV_REVISION",
  "OTelObserver",
  "OTelSpanHandle",
  "Agent",
  "CallbackRealtimeSession",
  "ConfigurationError",
  "ConflictError",
  "GuardrailTriggeredError",
  "ParseError",
  "ProviderHTTPError",
  "ProviderResponseTooLargeError",
  "ToolRegistry",
  "UnsupportedFeatureError",
  "ValidationError",
  "WORKFLOW_RUN_STATE_SCHEMA_VERSION",
  "WORKFLOW_EVALUATION_BASELINE_SCHEMA_VERSION",
  "WORKFLOW_EVALUATION_GATE_SCHEMA_VERSION",
  "WORKFLOW_STATE_RECORD_SCHEMA_VERSION",
  "ZhivexAIError",
  "agentApprovalResponsePart",
  "applySafetyPolicyToAgent",
  "assertTrustedEndpoint",
  "assistant",
  "cancelAgentRun",
  "cancelAgentRunTree",
  "collectUIMessage",
  "cosineSimilarity",
  "createAgent",
  "createAgentApprovalQueue",
  "createAgentApprovalMessage",
  "createAgentCapabilityRouter",
  "createAgentCapsule",
  "createAgentControlPlane",
  "createAgentControlPlaneRunRecord",
  "createAgentEvaluationFixture",
  "createAgentEvaluationReport",
  "createAgentHandoff",
  "createAgentHandoffMessage",
  "createAgentRunSnapshot",
  "createAgentRunLedger",
  "createAgentRunTreeSnapshot",
  "createAgentToolPolicy",
  "createAgentTraceArtifact",
  "createAgentTraceCollector",
  "cleanupFileArtifactStore",
  "createApprovalPolicy",
  "createBase64ArtifactData",
  "createBudgetGuard",
  "chunkText",
  "createCachedGenerateMiddleware",
  "createCircuitBreakerMiddleware",
  "createFileAgentMemoryStore",
  "createFileAgentRunStore",
  "createFileArtifactService",
  "createFileGenerateCache",
  "createFileSessionService",
  "createFileWorkflowStateService",
  "createHierarchicalAgentTrace",
  "createInMemoryAgentMemoryStore",
  "createInMemoryAgentRunStore",
  "createInMemoryArtifactService",
  "createInMemoryGenerateCache",
  "createInMemorySessionService",
  "createInMemoryWorkflowStateService",
  "createMcpToolSet",
  "createModelCatalog",
  "createMockLanguageModel",
  "createMockTool",
  "createPostgresAgentMemoryStore",
  "createPostgresAgentRunStore",
  "createPostgresArtifactService",
  "createPostgresSessionService",
  "createPostgresWorkflowStateService",
  "createProviderSupportDriftReport",
  "createProviderSupportMatrix",
  "createProductionSafetyPolicy",
  "createProductionTraceCollector",
  "createProductionTraceOptions",
  "createRedactionPolicy",
  "createRetrievalContextMessage",
  "createRunner",
  "createSafetyPolicy",
  "createSqliteAgentMemoryStore",
  "createSqliteAgentRunStore",
  "createSqliteArtifactService",
  "createSqliteSessionService",
  "createSqliteWorkflowStateService",
  "createSubAgentTool",
  "createTelemetryMiddleware",
  "createExternalArtifactReference",
  "createOtelAgentObserver",
  "createOtelObserver",
  "createOtelTelemetryMiddleware",
  "createOtelWorkflowObserver",
  "createTextMessage",
  "createToolRegistry",
  "createUIMessageJsonResponse",
  "createUIMessageLinesResponse",
  "createWorkflow",
  "compareWorkflowEvaluationReports",
  "createWorkflowEvaluationBaseline",
  "createWorkflowEvaluationDiffReport",
  "createWorkflowEvaluationFixture",
  "createWorkflowEvaluationReport",
  "decodeBase64WithLimit",
  "defaultModelCatalog",
  "diffAgentRunLedgers",
  "evaluateAgentBudgetPreflight",
  "audioPart",
  "embed",
  "embedMany",
  "embedRetrievalDocuments",
  "encodeAudioFrame",
  "encodeMediaFrame",
  "estimateAgentRunCost",
  "estimateTokenCost",
  "evaluateWorkflowEvaluationGate",
  "formatRetrievedContext",
  "fromUIMessage",
  "fromUIMessages",
  "generateGroundedText",
  "generateImage",
  "generateMusic",
  "generateObject",
  "generateSpeech",
  "generateText",
  "generateVideo",
  "getApiStability",
  "getAgentBudgetStatus",
  "getAgentApprovalRequestFromPart",
  "getAgentApprovalRequests",
  "getTextFromMessages",
  "getTextFromParts",
  "getToolCallsFromEvents",
  "inspectProviderAgentSupport",
  "inspectAgentCapsule",
  "inspectAgentControlPlane",
  "inspectFileArtifactStore",
  "isCallableToolDefinition",
  "isLoopbackHostname",
  "isPrivateNetworkHostname",
  "isToolRegistry",
  "judgeAgentEvaluation",
  "judgeWorkflowEvaluation",
  "loadWorkflowState",
  "listApiStability",
  "mergeAbortSignals",
  "migrateAgentRunState",
  "migrateAgentApprovalQueueItem",
  "migrateAgentCapsuleManifest",
  "migrateAgentRunLedger",
  "migrateArtifactRecord",
  "migrateAgentSessionRecord",
  "migrateWorkflowRunState",
  "migrateWorkflowStateRecord",
  "normalizeAgentSession",
  "normalizeAgentApprovalQueueItem",
  "normalizeAgentCapsuleManifest",
  "normalizeAgentRunLedger",
  "normalizeArtifactRecord",
  "normalizeWorkflowEvaluationBaseline",
  "pruneFileSessionStore",
  "pruneFileArtifactStore",
  "rankRetrievedDocuments",
  "readBodyWithLimit",
  "readErrorBodyWithLimit",
  "readJsonWithLimit",
  "normalizeFinishReason",
  "normalizeAgentRunState",
  "normalizeMessages",
  "normalizeWorkflowRunState",
  "normalizeWorkflowStateRecord",
  "openWebSocketConnection",
  "parseUIMessageRequest",
  "prepareSubagentsForAgent",
  "promoteAgentGoldenTrace",
  "providerDataPart",
  "renderProviderSupportMatrix",
  "retrieveContext",
  "replayAgentRun",
  "replayWorkflowRun",
  "resultMessages",
  "resolveArtifactServiceLimits",
  "resolveAudioResponseLimits",
  "resumeAgent",
  "runAgent",
  "runAgentEvaluation",
  "runAgentEvaluationFixture",
  "runAgentGroup",
  "runAgentHandoff",
  "runWorkflow",
  "runWorkflowEvaluation",
  "runWorkflowEvaluationFixture",
  "saveWorkflowEvaluationReportAsArtifact",
  "saveWorkflowOutputsAsArtifacts",
  "saveWorkflowReplayAsArtifact",
  "saveWorkflowState",
  "SESSION_SCHEMA_VERSION",
  "serializeJsonValue",
  "serializeUIMessage",
  "selectAgentModel",
  "streamAgent",
  "streamLiveAgent",
  "streamObject",
  "streamSpeech",
  "streamSSE",
  "streamText",
  "summarizeAgentTrace",
  "system",
  "textPart",
  "toSSEResponse",
  "toSSEStream",
  "toTextReadableStream",
  "toTextStreamResponse",
  "toToolSet",
  "toUIAgentStreamResponse",
  "toUIMessage",
  "toUIMessageStream",
  "toUIMessageStreamResponse",
  "toUIRunnerStreamResponse",
  "toUIMessages",
  "tool",
  "toolCallPart",
  "toolResultPart",
  "toolResultPayload",
  "transcribeAudio",
  "user",
  "unsupportedBrowserToken",
  "validateMessageParts",
  "verifyArtifactIntegrity",
  "verifyArtifactRecordIntegrity",
  "withRetry",
  "withTimeoutSignal",
  "wrapLanguageModel"
] as const;

const betaSymbols = [
  "ModelResolutionError",
  "createAgentExecutionEnvironmentBinding",
  "createAgentHarnessBinding",
  "MODEL_EVALUATION_REPORT_SCHEMA_VERSION",
  "cancelBatch",
  "cancelInteraction",
  "createBatch",
  "createContextCache",
  "fingerprintAgentHarness",
  "createAgentAuditRecord",
  "createFileSearchStore",
  "createContainsScorer",
  "createEmbeddingSimilarityScorer",
  "createExactMatchScorer",
  "createInteraction",
  "createJsonSchemaScorer",
  "createJsonValueScorer",
  "createMcpToolRegistry",
  "createModelJudgeScorer",
  "createModelResolver",
  "createMergedAbortSignal",
  "createProviderAdapter",
  "createRegexScorer",
  "createReadOnlyToolApprovalPolicy",
  "createSensitiveDataPolicy",
  "createToolCallScorer",
  "deleteBatch",
  "deleteContextCache",
  "deleteFile",
  "deleteFileSearchStore",
  "deleteInteraction",
  "deriveLegacyModelCapabilities",
  "deserializeUIMessage",
  "fetchPredictionOperation",
  "getAgentCapabilities",
  "getAgentSupportTier",
  "getBatch",
  "getContextCache",
  "getFile",
  "getFileSearchStore",
  "getHostedToolClass",
  "getInteraction",
  "hostedTool",
  "importFileToFileSearchStore",
  "isModelCapabilitySupported",
  "isHostedToolClass",
  "isHostedToolDefinition",
  "compareModelEvaluationReports",
  "listBatches",
  "listContextCaches",
  "listFileSearchStores",
  "listFiles",
  "MODEL_CAPABILITY_SUPPORT_LEVELS",
  "predictLongRunning",
  "predictRaw",
  "evaluateModelEvaluationGate",
  "resumeInteraction",
  "PRODUCTION_AGENT_KIT_SCHEMA_VERSION",
  "pruneFileWorkflowStateStore",
  "streamInteraction",
  "runModelEvaluation",
  "createToolAuditRecords",
  "uploadFile",
  "uploadToFileSearchStore"
] as const;

const experimentalSymbols = [
  "AdvancedToolRegistry",
  "createAdvancedToolRegistry",
  "createHttpTool",
  "createToolPermissionPreset",
  "createToolTestFixture",
  "experimentalRawProviderOptions",
  "googleCodeExecutionTool",
  "googleComputerUseTool",
  "googleFileSearchTool",
  "googleMapsTool",
  "googleSearchTool",
  "googleUrlContextTool",
  "inspectToolRegistry",
  "recordToolTestFixture",
  "runToolTestFixture",
  "testToolDefinition",
  "testToolRegistry"
] as const;

const createManifest = () => {
  const manifest: Record<string, ApiStabilityEntry> = {};

  for (const [stability, symbols] of [
    ["stable", stableSymbols],
    ["beta", betaSymbols],
    ["experimental", experimentalSymbols]
  ] as const) {
    for (const symbol of symbols) {
      if (manifest[symbol]) {
        throw new Error(`Duplicate API stability entry for ${symbol}`);
      }
      manifest[symbol] = { symbol, stability };
    }
  }

  return Object.freeze(manifest);
};

export const API_STABILITY_MANIFEST = createManifest();

export const getApiStability = (symbolName: string): ApiStabilityEntry | undefined =>
  API_STABILITY_MANIFEST[symbolName];

export const listApiStability = (level?: ApiStabilityLevel): ApiStabilityEntry[] =>
  Object.values(API_STABILITY_MANIFEST)
    .filter((entry) => level === undefined || entry.stability === level)
    .sort((a, b) => a.symbol.localeCompare(b.symbol));
