import { readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { maintenanceProviders, type MaintenanceProvider } from "./provider-registry.js";

const generatedHeader = "// Generated by scripts/sync-provider-registry.ts. Run bun run provider:sync.\n";
const sameIds = (actual: string[], expected: string[]) =>
  JSON.stringify([...actual].sort()) === JSON.stringify([...expected].sort());

/** Generate published metadata without importing maintenance code into a package. */
export async function renderProviderMetadata(repoRoot: string, registry: readonly MaintenanceProvider[] = maintenanceProviders) {
  const templates: Record<string, Record<string, string>> = {};
  for (const provider of [...registry].sort((a, b) => (a.scaffoldOrder ?? Infinity) - (b.scaffoldOrder ?? Infinity))) {
    const manifest = JSON.parse(await readFile(path.join(repoRoot, "packages", provider.id, "package.json"), "utf8"));
    if (manifest.name !== provider.packageName || typeof manifest.version !== "string" || !manifest.version) {
      throw new Error(`Provider manifest disagrees with registry: ${provider.id}`);
    }
    if (provider.scaffoldOrder === null) continue;
    if (!provider.defaultModel) throw new Error(`Missing scaffold default for ${provider.id}`);
    templates[provider.id] = {
      packageName: provider.packageName,
      packageVersion: manifest.version,
      factoryName: provider.factoryName,
      envName: provider.envName,
      defaultModel: provider.defaultModel
    };
  }
  const sdkManifest = JSON.parse(await readFile(path.join(repoRoot, "packages/sdk/package.json"), "utf8"));
  if (sdkManifest.name !== "@zhivex-ai/sdk" || typeof sdkManifest.version !== "string" || !sdkManifest.version) throw new Error("Missing SDK scaffold release version");
  return new Map([
    ["packages/sdk/src/provider-templates.generated.ts", `${generatedHeader}export const sdkScaffoldVersion: string = ${JSON.stringify(sdkManifest.version)};\n\ninterface ProviderTemplateMetadata {\n  readonly packageName: string;\n  readonly packageVersion: string;\n  readonly factoryName: string;\n  readonly envName: string;\n  readonly defaultModel: string;\n}\n\nexport const providerTemplates: Readonly<Record<${Object.keys(templates).map(id => JSON.stringify(id)).join(" | ")}, ProviderTemplateMetadata>> = ${JSON.stringify(templates, null, 2)};\n`],
    ["packages/sdk/src/catalog/fragments.ts", `${generatedHeader}${registry.map(p => `import { ${p.catalogExport} } from "./providers/${p.id}.js";`).join("\n")}\n\nexport const defaultModelCatalogFragments = Object.freeze([\n${registry.map(p => `  ${p.catalogExport}`).join(",\n")}\n]);\n`]
  ]);
}

/** Check inventories that have their own package boundary rather than importing registry runtime data. */
export async function validateProviderInventories(repoRoot: string, registry: readonly MaintenanceProvider[] = maintenanceProviders): Promise<string[]> {
  const errors: string[] = [];
  const ids = registry.map(p => p.id);
  if (new Set(ids).size !== ids.length) errors.push("Duplicate provider registry ID");
  const orders = registry.filter(p => p.scaffoldOrder !== null).map(p => p.scaffoldOrder);
  if (new Set(orders).size !== orders.length) errors.push("Duplicate scaffold order");
  const types = await readFile(path.join(repoRoot, "packages/gateway/src/types.ts"), "utf8");
  const union = types.match(/export type GatewayProviderId\s*=([\s\S]*?);/)?.[1] ?? "";
  if (!sameIds([...union.matchAll(/"([^\"]+)"/g)].map(m => m[1]!), ids)) errors.push("GatewayProviderId disagrees with provider registry");
  const gateway = await readFile(path.join(repoRoot, "packages/gateway/src/index.ts"), "utf8");
  const set = gateway.match(/const GATEWAY_PROVIDERS = new Set<GatewayProviderId>\(\[([\s\S]*?)\]\)/)?.[1] ?? "";
  if (!sameIds([...set.matchAll(/"([^\"]+)"/g)].map(m => m[1]!), ids)) errors.push("GATEWAY_PROVIDERS disagrees with provider registry");
  const references = JSON.parse(await readFile(path.join(repoRoot, "tsconfig.json"), "utf8")).references as { path: string }[];
  const catalogIds = (await readdir(path.join(repoRoot, "packages/sdk/src/catalog/providers"))).filter(n => n.endsWith(".ts")).map(n => n.slice(0, -3));
  if (!sameIds(catalogIds, ids)) errors.push("Catalog fragment files disagree with provider registry");
  for (const p of registry) {
    if (!references.some(r => r.path === `./packages/${p.id}`)) errors.push(`Missing TypeScript project reference: ${p.id}`);
    const source = await readFile(path.join(repoRoot, "packages", p.id, "src/index.ts"), "utf8");
    if (!new RegExp(`export\\s+(?:const|function)\\s+${p.factoryName}\\b`).test(source)) errors.push(`Missing provider factory export: ${p.factoryName}`);
    const fragment = await readFile(path.join(repoRoot, "packages/sdk/src/catalog/providers", `${p.id}.ts`), "utf8");
    if (!fragment.includes(`export const ${p.catalogExport}`) || !fragment.includes(`provider: "${p.id}"`)) errors.push(`Catalog fragment identity disagrees: ${p.id}`);
    const modelIds = [...fragment.matchAll(/(?:"modelId"|modelId)\s*:\s*"([^"]+)"/g)].map(m => m[1]!);
    const aliases = [...fragment.matchAll(/(?:"aliases"|aliases)\s*:\s*\[([^\]]*)\]/g)].flatMap(m => [...m[1]!.matchAll(/"([^"]+)"/g)].map(alias => alias[1]!));
    if (p.defaultModel && ![...modelIds, ...aliases].includes(p.defaultModel)) errors.push(`Scaffold default missing from catalog: ${p.id}/${p.defaultModel}`);
  }
  return errors;
}

export async function syncProviderRegistry(repoRoot: string, check = false): Promise<string[]> {
  const errors = await validateProviderInventories(repoRoot);
  if (errors.length && !check) return errors;
  const outputs = await renderProviderMetadata(repoRoot);
  for (const [relativePath, expected] of outputs) {
    let actual: string | undefined;
    try { actual = await readFile(path.join(repoRoot, relativePath), "utf8"); }
    catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; }
    if (actual === expected) continue;
    if (check) errors.push(`Generated provider metadata is stale: ${relativePath}`);
    else await writeFile(path.join(repoRoot, relativePath), expected);
  }
  return errors;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const errors = await syncProviderRegistry(path.resolve(import.meta.dirname, ".."), process.argv.includes("--check"));
  if (errors.length) { console.error(errors.join("\n")); process.exitCode = 1; }
  else console.log("Provider registry metadata and package inventories are aligned.");
}
